spring.application.name=TickNet

spring.datasource.url=jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.sbmdvssltberglrumtzt
spring.datasource.password=Billetterie15
spring.datasource.driver-class-name=org.postgresql.Driver

# CRITICAL FOR PORT 6543:
spring.datasource.hikari.data-source-properties.prepareThreshold=0

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080

spring.flyway.enabled=false