spring.application.name=TickNet

spring.datasource.url=jdbc:postgresql://db.sbmdvssltberglrumtzt.supabase.co:6543/postgres?sslmode=require
spring.datasource.username=postgres

# juste pour tester, le mdp sera changer et supprimer
spring.datasource.password=Billetterie15
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=false
spring.jackson.serialization.fail-on-empty-beans=false

springdoc.swagger-ui.path=/swagger-ui-custom.html
springdoc.swagger-ui.operationsSorter=method

server.port=8080