spring.application.name=TickNet

# Spring Boot PostgreSQL JDBC, JPA and Hibernate Properties
spring.datasource.url=jdbc:postgresql://localhost:5432/ticknet_db
spring.datasource.username=ticknet_user
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Thymeleaf configuration
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Server port
server.port=8080
